script to fetch Clearbit data via API, merge resulting data into email-map file
cncf/gitdm.archive pull request #17
Opened 2017-12-05 14:10 UTC by radoslaw

2017-12-06 16:25 UTC, radoslaw commented
code was refactored to fall withinsingle digits checking by rubocop, variable names are now more explicit

2017-12-11 12:35 UTC, dankohn commented on merge_clearbit_affiliations_into_map.rb
> +    affiliation_suggestion = 'independent' if company_name&.include? selfie
Independent

2017-12-11 21:25 UTC, lukaszgryglicki commented
More tools will require changing "Self" to "Independent" in addition to this one.

2017-12-19 09:23 UTC, lukaszgryglicki requested changes
So finally:
1. I would split replace 'Self' with 'Independent' to a separate PR, because it is hard to see actual new affiliations in this PR (not absolutely necessary)
2. I would *NOT* add "notFound" entries unless You manually checked all possible sources and You gave up. Do *NOT* set "NotFound" just because some automatic tool didn't find affiliations. NotFound is to be used as a marker for emails that were researched in all possible ways and failed to be processed.
3. Manually review email-map before creating PR - few items are not emails addresses.

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +
Get rid of empty lines

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +248 NotFound
`248` is not an email

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +32553353+jgoldbergstackoverdrive!users.noreply.github.com NotFound
You can only mark email with "Not Found" when You manually researched that email using google, linkedin and all possible sources. Do not mark emails as NotFound if they were not found by a single automatic tool.
"NotFound" serves as a marker that email was researched in many ways and none of them found affiliation, most important: MANUALLY!

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +400 NotFound
400 is not an email.
There are more like this.
Please QA Your work, especially this file must be reviewed manually every time - this MUST be correct.

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +beethoven1110!gmail.com missing_name
missing_name doesn't seem to be a company name

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +bo0merzzz!gmail.com SAP Labs Bulgaria
Labs means Independent?

2017-12-19 09:23 UTC, lukaszgryglicki commented on cncf-config/email-map
> +ema!linux.it Linux
Hmmm... Linux?

2017-12-19 11:38 UTC, closed without merging

2017-12-19 11:40 UTC, radoslaw commented
my branch went berserk, will create a slimmer PR with edited code