Updating the details on Samsung SDS
cncf/gitdm.archive pull request #59
Opened 2018-07-11 17:29 UTC by mattfarina

This makes the Samsung SDS material consistent and up to date.

2018-07-11 17:37 UTC, lukaszgryglicki commented
Will take a look tomorrow, its almost 8 PM in Poland now. Thanks for the PR.

2018-07-12 04:39 UTC, lukaszgryglicki requested changes
No new affiliations specified - only "date to" added. Please add new affiliations, or specify Idndependent. Or specify that there will be no new affiliations, then after each end date we will have unknown affiliations.

2018-07-12 04:39 UTC, lukaszgryglicki commented on developers_affiliations.txt
> +	Samsung SDS until 2018-05-11
If we change affiliation by providing end date, the we should specify new affiliation after this or say "Independent". Otherwise the new affiliation will be Unknown.

2018-07-12 04:39 UTC, lukaszgryglicki commented on developers_affiliations.txt
> +	Samsung SDS until 2017-12-31
If we change affiliation by providing end date, the we should specify new affiliation after this or say "Independent". Otherwise the new affiliation will be Unknown.

2018-07-12 04:39 UTC, lukaszgryglicki commented on developers_affiliations.txt
> +	Samsung SDS until 2018-05-25
If we change affiliation by providing end date, the we should specify new affiliation after this or say "Independent". Otherwise the new affiliation will be Unknown.

2018-07-13 20:07 UTC, mattfarina commented on developers_affiliations.txt
> +	Samsung SDS until 2018-05-25
Updated with new detail

2018-07-13 20:07 UTC, mattfarina commented on developers_affiliations.txt
> +	Samsung SDS until 2017-12-31
Updated with new detail

2018-07-13 20:07 UTC, mattfarina commented on developers_affiliations.txt
> +	Samsung SDS until 2018-05-11
Updated with new detail

2018-07-13 20:07 UTC, mattfarina commented
@lukaszgryglicki I updated the PR with those details.

2018-07-13 20:15 UTC, lukaszgryglicki commented
Thanks - will merge next week.

2018-07-16 08:22 UTC, merged