Add instructions for a non-cncf project/org.
cncf/gitdm.archive pull request #60
Opened 2018-07-13 17:00 UTC by IsAmrish

2018-07-13 17:30 UTC, lukaszgryglicki requested changes

2018-07-13 17:30 UTC, lukaszgryglicki commented on SYNC.md
> +
I would love to add this description but please create a separate md file and put a link to this file in SYNC.md or in README.md or in both.
I just want to have more smaller md files.
Thanks.

2018-07-13 20:52 UTC, IsAmrish commented on SYNC.md
> +
sure, Thanks

2018-07-13 21:16 UTC, IsAmrish commented
@lukaszgryglicki  I have seperated instructions in ADD_PROJECT.md file. Also, I have added links to both README.md and SYNC.md file.

2018-07-14 05:18 UTC, merged

2018-07-14 05:19 UTC, lukaszgryglicki commented
Merged, thanks.