Rad
cncf/gitdm.archive pull request #7
Opened 2017-11-02 17:38 UTC by radoslaw

Please review as I added 390 entries from a 550 records file

2017-11-02 17:54 UTC, lukaszgryglicki requested changes
Please address review feedback.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +zzxwill!gmail.com Self
Please sort email-map file:
For example:
`cat cncf-config/email-map | sort | uniq > out; mv out cncf-condig/email-map`

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +me!ataylor.io Aaron Taylor
Looks like the guy's name, so it should be "Self"?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +chris!soundshare.co.uk Chris Stryczynski
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +william.allen!civitaslearning.com Civitas Learning
Everything with "learning" in its name is suspected to be Self.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +tamird!gmail.com Cockroach Labs
For every company please try to normalize it. I mean that sometimes people name the same company in a very large number of variabnt, in this case it is worth to check if we do already have "Cockroach" company?

The same for example for:
Samsung SDS, Samsund Co., Samsung corp. etc.
They're all just Samsung.

We don't want pieces like: Co., Ltd., Corp., Inc., Limited., LLC, Group. in names.
Also normalize samsung, Samsung, SAMSUNG etc.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +radhika.dwaraka!gmail.com Columbia University
University usually means Self

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +david!davidwelch.co David Welch
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +aprativadi!gmail.com false
false?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +jdolitsky!gmail.com HERE
Is there company named HERE?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +cs15btech11007!iith.ac.in Indian Inst of Technology Hyderabad
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +james!federacy.com James Sulinski
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +justin!balduncle.com Justin Johnson
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +du!njtech.edu.cn Nanjing University of Technology
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +ruben!rocketeer.be Ruben Vermeersch
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +chlunde!ifi.uio.no University of Oslo
Self?

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +emanic!users.noreply.github.com tigera
Tigera. Check all Your affiliatios without case sensitive to avoid uplicate company names with different upper/lower case, capitalization.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +dmyerscough!users.noreply.github.com Uber
I think we have Uber but spelled differently.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +s1499k005!gmail.com self
Uppercase Self

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +freemaneben!gmail.com self
Same 2 more.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +kfirstar!gmail.com UniqueNerd
Same here.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +mathspanda826!gmail.com Tongji University
Self

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +liquidnuker@gmail.com not found
Don't add "not found" guys. If You're really sure that You cannot find it - use special value "NotFound"

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +andrea.melloncelli!gmail.com self
capitalize.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +Gsampowers!gmail.com self
capitalize.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +tigerlinux!gmail.com self
self.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +msvbhat!gmail.com Unbxd Inc
+2.

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +shanse!gmail.com self
+2

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +andrew!areed.io self
+1

2017-11-02 17:54 UTC, lukaszgryglicki commented on cncf-config/email-map
> +2ffs2nns!gmail.com tigera
Tigera.
Summing up:
- Sort
- Normalize names
- Case sensitivity
- Maximize reuse existing company names.

2017-11-02 17:59 UTC, dankohn commented
Thanks for the careful review. However note that for odd reasons, Samsung
SDS is a separate company from Samsung, Samsung Electronics and Samsung
Mobile (the latter 3 can all be Samsung). But I agree with everything else.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Thu, Nov 2, 2017 at 1:54 PM, Łukasz Gryglicki <notifications@github.com>
wrote:

> *@lukaszgryglicki* requested changes on this pull request.
>
> Please address review feedback.
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148607945>:
>
> > \ No newline at end of file
> +zzxwill!gmail.com Self
>
> Please sort email-map file:
> For example:
> cat cncf-config/email-map | sort | uniq > out; mv out cncf-condig/email-map
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148608061>:
>
> > \ No newline at end of file
> +zzxwill!gmail.com Self
> +sebastien!emmene-moi.fr emmene-moi
> +me!ataylor.io Aaron Taylor
>
> Looks like the guy's name, so it should be "Self"?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148608211>:
>
> > +matlan!amazon.com Amazon.com
> +maruf!appscode.com AppsCode
> +alon!argus-sec.com Argus Cyber Security
> +hblanks!artifex.org Artifex.org
> +matth.maq!gmail.com At The Corner
> +will!autonomic.ai Autonomic
> +chenguoyan01!baidu.com Baidu
> +carrodher1179!gmail.com Bitnami
> +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
>
> Self?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148608311>:
>
> > +maruf!appscode.com AppsCode
> +alon!argus-sec.com Argus Cyber Security
> +hblanks!artifex.org Artifex.org
> +matth.maq!gmail.com At The Corner
> +will!autonomic.ai Autonomic
> +chenguoyan01!baidu.com Baidu
> +carrodher1179!gmail.com Bitnami
> +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
>
> Everything with "learning" in its name is suspected to be Self.
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609056>:
>
> > +carrodher1179!gmail.com Bitnami
> +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
> +satyam.zode!cloudbyte.com CloudByte
> +erick.tryzelaar!gmail.com Cloudera
> +adam.schepis!gmail.com CloudHealth Technologies
> +zackproser!gmail.com Cloudmark
> +jordanthelewis!gmail.com Cockroach Labs
> +tamird!gmail.com Cockroach Labs
>
> For every company please try to normalize it. I mean that sometimes people
> name the same company in a very large number of variabnt, in this case it
> is worth to check if we do already have "Cockroach" company?
>
> The same for example for:
> Samsung SDS, Samsund Co., Samsung corp. etc.
> They're all just Samsung.
>
> We don't want pieces like: Co., Ltd., Corp., Inc., Limited., LLC, Group.
> in names.
> Also normalize samsung, Samsung, SAMSUNG etc.
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609160>:
>
> > +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
> +satyam.zode!cloudbyte.com CloudByte
> +erick.tryzelaar!gmail.com Cloudera
> +adam.schepis!gmail.com CloudHealth Technologies
> +zackproser!gmail.com Cloudmark
> +jordanthelewis!gmail.com Cockroach Labs
> +tamird!gmail.com Cockroach Labs
> +radhika.dwaraka!gmail.com Columbia University
>
> University usually means Self
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609318>:
>
> > +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
> +satyam.zode!cloudbyte.com CloudByte
> +erick.tryzelaar!gmail.com Cloudera
> +adam.schepis!gmail.com CloudHealth Technologies
> +zackproser!gmail.com Cloudmark
> +jordanthelewis!gmail.com Cockroach Labs
> +tamird!gmail.com Cockroach Labs
> +radhika.dwaraka!gmail.com Columbia University
> +anonymuse!gmail.com Contino
> +bruno!bronosky.com Cox Media Group
> +marcelo.grebois!daimler.com Daimler
> +dirbaio!dirbaio.net Dario Nieuwenhuis
> +shashank.pradhan!datadoghq.com Datadog
> +david!davidwelch.co David Welch
>
> Self?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609472>:
>
> > +david!davidwelch.co David Welch
> +deni!denibertovic.com Deni Bertovic
> +joonas!bergi.us DigitalOcean
> +martin!etmajer.com Dynatrace
> +alexander.brandstedt!ea.com Electronic Arts
> +mterry!ea.com Electronic Arts
> +aaron.peschel!gmail.com Element Analytics
> +maxime.guyot!elits.com ELITS
> +b.klein!epages.com ePages
> +martin.joehren!esailors.de eSailors IT solutions
> +ryan!espressive.com Espressive
> +sergio.moreno.calzada!everis.com Everis
> +davithomas!lonc02rw2h8g8wl.sea.corp.expecn.com Expedia
> +ldemailly!gmail.com Facebook
> +catherinec!fair.com Fair
> +aprativadi!gmail.com false
>
> false?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609612>:
>
> > +catherinec!fair.com Fair
> +aprativadi!gmail.com false
> +tadas.subonis!gmail.com Feedpresso
> +niels-ole.kuehl!flixbus.com FlixBus
> +radek!dataminelab.com Framework Training
> +core!futurequest.net Futurequest
> +jimmyjones2!gmx.co.uk GMX
> +evgeny.shmarnev!gooddata.com GoodData
> +dan.isla!gmail.com Google
> +andybons!gmail.com Google
> +ahmet.kizilay!gmail.com Graph Commons
> +klizhentas!gmail.com Gravitational
> +sean.clemmer!greenhouse.io Greenhouse Software
> +mmarchetti!hearst.com Hearst
> +jrondeau!heptio.com Heptio
> +jdolitsky!gmail.com HERE
>
> Is there company named HERE?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609679>:
>
> > +jimmyjones2!gmx.co.uk GMX
> +evgeny.shmarnev!gooddata.com GoodData
> +dan.isla!gmail.com Google
> +andybons!gmail.com Google
> +ahmet.kizilay!gmail.com Graph Commons
> +klizhentas!gmail.com Gravitational
> +sean.clemmer!greenhouse.io Greenhouse Software
> +mmarchetti!hearst.com Hearst
> +jrondeau!heptio.com Heptio
> +jdolitsky!gmail.com HERE
> +chris.koehnke!gmail.com Heureka
> +sjevsejev!gmail.com home24
> +poweld!gmail.com HubSpot
> +markus.padourek!gmail.com Hufsy
> +denverdino!gmail.com IBM
> +cs15btech11007!iith.ac.in Indian Inst of Technology Hyderabad
>
> Self?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609720>:
>
> > +andybons!gmail.com Google
> +ahmet.kizilay!gmail.c [...]

2017-11-02 18:12 UTC, lukaszgryglicki commented
Thanks for the info, I didn't know that.

2017-11-03 08:55 UTC, radoslaw commented
I will review all the email/employer records in question

Rad
 

    On Thursday, November 2, 2017, 6:59:14 PM GMT+1, Dan Kohn <notifications@github.com> wrote:  
 
 Thanks for the careful review. However note that for odd reasons, Samsung
SDS is a separate company from Samsung, Samsung Electronics and Samsung
Mobile (the latter 3 can all be Samsung). But I agree with everything else.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Thu, Nov 2, 2017 at 1:54 PM, Łukasz Gryglicki <notifications@github.com>
wrote:

> *@lukaszgryglicki* requested changes on this pull request.
>
> Please address review feedback.
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148607945>:
>
> > \ No newline at end of file
> +zzxwill!gmail.com Self
>
> Please sort email-map file:
> For example:
> cat cncf-config/email-map | sort | uniq > out; mv out cncf-condig/email-map
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148608061>:
>
> > \ No newline at end of file
> +zzxwill!gmail.com Self
> +sebastien!emmene-moi.fr emmene-moi
> +me!ataylor.io Aaron Taylor
>
> Looks like the guy's name, so it should be "Self"?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148608211>:
>
> > +matlan!amazon.com Amazon.com
> +maruf!appscode.com AppsCode
> +alon!argus-sec.com Argus Cyber Security
> +hblanks!artifex.org Artifex.org
> +matth.maq!gmail.com At The Corner
> +will!autonomic.ai Autonomic
> +chenguoyan01!baidu.com Baidu
> +carrodher1179!gmail.com Bitnami
> +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
>
> Self?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148608311>:
>
> > +maruf!appscode.com AppsCode
> +alon!argus-sec.com Argus Cyber Security
> +hblanks!artifex.org Artifex.org
> +matth.maq!gmail.com At The Corner
> +will!autonomic.ai Autonomic
> +chenguoyan01!baidu.com Baidu
> +carrodher1179!gmail.com Bitnami
> +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
>
> Everything with "learning" in its name is suspected to be Self.
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609056>:
>
> > +carrodher1179!gmail.com Bitnami
> +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
> +satyam.zode!cloudbyte.com CloudByte
> +erick.tryzelaar!gmail.com Cloudera
> +adam.schepis!gmail.com CloudHealth Technologies
> +zackproser!gmail.com Cloudmark
> +jordanthelewis!gmail.com Cockroach Labs
> +tamird!gmail.com Cockroach Labs
>
> For every company please try to normalize it. I mean that sometimes people
> name the same company in a very large number of variabnt, in this case it
> is worth to check if we do already have "Cockroach" company?
>
> The same for example for:
> Samsung SDS, Samsund Co., Samsung corp. etc.
> They're all just Samsung.
>
> We don't want pieces like: Co., Ltd., Corp., Inc., Limited., LLC, Group.
> in names.
> Also normalize samsung, Samsung, SAMSUNG etc.
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609160>:
>
> > +frederikns!gmail.com Blackwood Seven
> +donovan_aaron!bah.com Booz Allen Hamilton
> +andre!brpx.com Bright Pixel
> +james.keogh!cambridgeconsultants.com Cambridge Consultants
> +vagees!gmail.com Capital One
> +plaintext!andromedarabbit.net CHOI, Jaehoon
> +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
> +satyam.zode!cloudbyte.com CloudByte
> +erick.tryzelaar!gmail.com Cloudera
> +adam.schepis!gmail.com CloudHealth Technologies
> +zackproser!gmail.com Cloudmark
> +jordanthelewis!gmail.com Cockroach Labs
> +tamird!gmail.com Cockroach Labs
> +radhika.dwaraka!gmail.com Columbia University
>
> University usually means Self
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609318>:
>
> > +chris!chrismoos.com Chris Moos
> +chris!soundshare.co.uk Chris Stryczynski
> +william.allen!civitaslearning.com Civitas Learning
> +satyam.zode!cloudbyte.com CloudByte
> +erick.tryzelaar!gmail.com Cloudera
> +adam.schepis!gmail.com CloudHealth Technologies
> +zackproser!gmail.com Cloudmark
> +jordanthelewis!gmail.com Cockroach Labs
> +tamird!gmail.com Cockroach Labs
> +radhika.dwaraka!gmail.com Columbia University
> +anonymuse!gmail.com Contino
> +bruno!bronosky.com Cox Media Group
> +marcelo.grebois!daimler.com Daimler
> +dirbaio!dirbaio.net Dario Nieuwenhuis
> +shashank.pradhan!datadoghq.com Datadog
> +david!davidwelch.co David Welch
>
> Self?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609472>:
>
> > +david!davidwelch.co David Welch
> +deni!denibertovic.com Deni Bertovic
> +joonas!bergi.us DigitalOcean
> +martin!etmajer.com Dynatrace
> +alexander.brandstedt!ea.com Electronic Arts
> +mterry!ea.com Electronic Arts
> +aaron.peschel!gmail.com Element Analytics
> +maxime.guyot!elits.com ELITS
> +b.klein!epages.com ePages
> +martin.joehren!esailors.de eSailors IT solutions
> +ryan!espressive.com Espressive
> +sergio.moreno.calzada!everis.com Everis
> +davithomas!lonc02rw2h8g8wl.sea.corp.expecn.com Expedia
> +ldemailly!gmail.com Facebook
> +catherinec!fair.com Fair
> +aprativadi!gmail.com false
>
> false?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609612>:
>
> > +catherinec!fair.com Fair
> +aprativadi!gmail.com false
> +tadas.subonis!gmail.com Feedpresso
> +niels-ole.kuehl!flixbus.com FlixBus
> +radek!dataminelab.com Framework Training
> +core!futurequest.net Futurequest
> +jimmyjones2!gmx.co.uk GMX
> +evgeny.shmarnev!gooddata.com GoodData
> +dan.isla!gmail.com Google
> +andybons!gmail.com Google
> +ahmet.kizilay!gmail.com Graph Commons
> +klizhentas!gmail.com Gravitational
> +sean.clemmer!greenhouse.io Greenhouse Software
> +mmarchetti!hearst.com Hearst
> +jrondeau!heptio.com Heptio
> +jdolitsky!gmail.com HERE
>
> Is there company named HERE?
> ------------------------------
>
> In cncf-config/email-map
> <https://github.com/cncf/gitdm/pull/7#discussion_r148609679>:
>
> > +jimmyjones2!gmx.co.uk GMX
> +evgeny.shmarnev!gooddata.com GoodData
> +dan.isla!gmail.com Google
> +andybons!gmail.com Google
> +ahmet.kizilay!gmail.com Graph Commons
> +klizhentas!gmail.com Gravitational
> +sean.clemmer!greenhouse.io Greenhouse Software
> +mmarchetti!hearst.com Hearst
> +jrondeau!heptio.com Heptio
> +jdolitsky!gmail.com HERE
> +chris.koehnke!gmail.com Heureka
> +sjevsejev!gmail.com home24
> +poweld!gmail.com HubSpot
> +markus.padourek!gmail.com Hufsy
> +denverdino!gmail.com IBM
> +cs15btech11007!iith.ac.in Indian Inst of Technology Hyderabad
>
> Self?
> --------------- [...]

2017-11-03 13:27 UTC, radoslaw commented
all changes done as requested or better
yes, there is a company called HERE (here.com)
about uber, there was Uberous but it turned out to be Self for the email address on that record

Rad

    On Thursday, November 2, 2017, 6:54:42 PM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
@lukaszgryglicki requested changes on this pull request.

Please address review feedback.

In cncf-config/email-map:
> \ No newline at end of file
+zzxwill!gmail.com Self

Please sort email-map file:
For example:
cat cncf-config/email-map | sort | uniq > out; mv out cncf-condig/email-map

In cncf-config/email-map:
> \ No newline at end of file
+zzxwill!gmail.com Self
+sebastien!emmene-moi.fr emmene-moi
+me!ataylor.io Aaron Taylor

Looks like the guy's name, so it should be "Self"?

In cncf-config/email-map:
> +matlan!amazon.com Amazon.com
+maruf!appscode.com AppsCode
+alon!argus-sec.com Argus Cyber Security
+hblanks!artifex.org Artifex.org
+matth.maq!gmail.com At The Corner
+will!autonomic.ai Autonomic
+chenguoyan01!baidu.com Baidu
+carrodher1179!gmail.com Bitnami
+frederikns!gmail.com Blackwood Seven
+donovan_aaron!bah.com Booz Allen Hamilton
+andre!brpx.com Bright Pixel
+james.keogh!cambridgeconsultants.com Cambridge Consultants
+vagees!gmail.com Capital One
+plaintext!andromedarabbit.net CHOI, Jaehoon
+chris!chrismoos.com Chris Moos
+chris!soundshare.co.uk Chris Stryczynski

Self?

In cncf-config/email-map:
> +maruf!appscode.com AppsCode
+alon!argus-sec.com Argus Cyber Security
+hblanks!artifex.org Artifex.org
+matth.maq!gmail.com At The Corner
+will!autonomic.ai Autonomic
+chenguoyan01!baidu.com Baidu
+carrodher1179!gmail.com Bitnami
+frederikns!gmail.com Blackwood Seven
+donovan_aaron!bah.com Booz Allen Hamilton
+andre!brpx.com Bright Pixel
+james.keogh!cambridgeconsultants.com Cambridge Consultants
+vagees!gmail.com Capital One
+plaintext!andromedarabbit.net CHOI, Jaehoon
+chris!chrismoos.com Chris Moos
+chris!soundshare.co.uk Chris Stryczynski
+william.allen!civitaslearning.com Civitas Learning

Everything with "learning" in its name is suspected to be Self.

In cncf-config/email-map:
> +carrodher1179!gmail.com Bitnami
+frederikns!gmail.com Blackwood Seven
+donovan_aaron!bah.com Booz Allen Hamilton
+andre!brpx.com Bright Pixel
+james.keogh!cambridgeconsultants.com Cambridge Consultants
+vagees!gmail.com Capital One
+plaintext!andromedarabbit.net CHOI, Jaehoon
+chris!chrismoos.com Chris Moos
+chris!soundshare.co.uk Chris Stryczynski
+william.allen!civitaslearning.com Civitas Learning
+satyam.zode!cloudbyte.com CloudByte
+erick.tryzelaar!gmail.com Cloudera
+adam.schepis!gmail.com CloudHealth Technologies
+zackproser!gmail.com Cloudmark
+jordanthelewis!gmail.com Cockroach Labs
+tamird!gmail.com Cockroach Labs

For every company please try to normalize it. I mean that sometimes people name the same company in a very large number of variabnt, in this case it is worth to check if we do already have "Cockroach" company?

The same for example for:
Samsung SDS, Samsund Co., Samsung corp. etc.
They're all just Samsung.

We don't want pieces like: Co., Ltd., Corp., Inc., Limited., LLC, Group. in names.
Also normalize samsung, Samsung, SAMSUNG etc.

In cncf-config/email-map:
> +frederikns!gmail.com Blackwood Seven
+donovan_aaron!bah.com Booz Allen Hamilton
+andre!brpx.com Bright Pixel
+james.keogh!cambridgeconsultants.com Cambridge Consultants
+vagees!gmail.com Capital One
+plaintext!andromedarabbit.net CHOI, Jaehoon
+chris!chrismoos.com Chris Moos
+chris!soundshare.co.uk Chris Stryczynski
+william.allen!civitaslearning.com Civitas Learning
+satyam.zode!cloudbyte.com CloudByte
+erick.tryzelaar!gmail.com Cloudera
+adam.schepis!gmail.com CloudHealth Technologies
+zackproser!gmail.com Cloudmark
+jordanthelewis!gmail.com Cockroach Labs
+tamird!gmail.com Cockroach Labs
+radhika.dwaraka!gmail.com Columbia University

University usually means Self

In cncf-config/email-map:
> +chris!chrismoos.com Chris Moos
+chris!soundshare.co.uk Chris Stryczynski
+william.allen!civitaslearning.com Civitas Learning
+satyam.zode!cloudbyte.com CloudByte
+erick.tryzelaar!gmail.com Cloudera
+adam.schepis!gmail.com CloudHealth Technologies
+zackproser!gmail.com Cloudmark
+jordanthelewis!gmail.com Cockroach Labs
+tamird!gmail.com Cockroach Labs
+radhika.dwaraka!gmail.com Columbia University
+anonymuse!gmail.com Contino
+bruno!bronosky.com Cox Media Group
+marcelo.grebois!daimler.com Daimler
+dirbaio!dirbaio.net Dario Nieuwenhuis
+shashank.pradhan!datadoghq.com Datadog
+david!davidwelch.co David Welch

Self?

In cncf-config/email-map:
> +david!davidwelch.co David Welch
+deni!denibertovic.com Deni Bertovic
+joonas!bergi.us DigitalOcean
+martin!etmajer.com Dynatrace
+alexander.brandstedt!ea.com Electronic Arts
+mterry!ea.com Electronic Arts
+aaron.peschel!gmail.com Element Analytics
+maxime.guyot!elits.com ELITS
+b.klein!epages.com ePages
+martin.joehren!esailors.de eSailors IT solutions
+ryan!espressive.com Espressive
+sergio.moreno.calzada!everis.com Everis
+davithomas!lonc02rw2h8g8wl.sea.corp.expecn.com Expedia
+ldemailly!gmail.com Facebook
+catherinec!fair.com Fair
+aprativadi!gmail.com false

false?

In cncf-config/email-map:
> +catherinec!fair.com Fair
+aprativadi!gmail.com false
+tadas.subonis!gmail.com Feedpresso
+niels-ole.kuehl!flixbus.com FlixBus
+radek!dataminelab.com Framework Training
+core!futurequest.net Futurequest
+jimmyjones2!gmx.co.uk GMX
+evgeny.shmarnev!gooddata.com GoodData
+dan.isla!gmail.com Google
+andybons!gmail.com Google
+ahmet.kizilay!gmail.com Graph Commons
+klizhentas!gmail.com Gravitational
+sean.clemmer!greenhouse.io Greenhouse Software
+mmarchetti!hearst.com Hearst
+jrondeau!heptio.com Heptio
+jdolitsky!gmail.com HERE

Is there company named HERE?

In cncf-config/email-map:
> +jimmyjones2!gmx.co.uk GMX
+evgeny.shmarnev!gooddata.com GoodData
+dan.isla!gmail.com Google
+andybons!gmail.com Google
+ahmet.kizilay!gmail.com Graph Commons
+klizhentas!gmail.com Gravitational
+sean.clemmer!greenhouse.io Greenhouse Software
+mmarchetti!hearst.com Hearst
+jrondeau!heptio.com Heptio
+jdolitsky!gmail.com HERE
+chris.koehnke!gmail.com Heureka
+sjevsejev!gmail.com home24
+poweld!gmail.com HubSpot
+markus.padourek!gmail.com Hufsy
+denverdino!gmail.com IBM
+cs15btech11007!iith.ac.in Indian Inst of Technology Hyderabad

Self?

In cncf-config/email-map:
> +andybons!gmail.com Google
+ahmet.kizilay!gmail.com Graph Commons
+klizhentas!gmail.com Gravitational
+sean.clemmer!greenhouse.io Greenhouse Software
+mmarchetti!hearst.com Hearst
+jrondeau!heptio.com Heptio
+jdolitsky!gmail.com HERE
+chris.koehnke!gmail.com Heureka
+sjevsejev!gmail.com home24
+poweld!gmail.com HubSpot
+markus.padourek!gmail.com Hufsy
+denverdino!gmail.com IBM
+cs15btech11007!iith.ac.in Indian Inst of Technology Hyderabad
+olivier.grisel!ensta.org Inria
+khris.richardson!gmail.com Intel
+james!federacy.com James Sulinski

Self?

In cncf-config/email-map:
> +sean.clemmer!greenhouse.io Greenhouse Software
+mmarchetti!hearst.com Hearst
+jrondeau!heptio.com Heptio
+jdolitsky!gmail.com HERE
+chris.koehnke!gmail.com Heureka
+sjevsejev!gmail.com home24
+poweld!gmail.com HubSpot
+markus.padourek!gmail.com Hufsy
+denverdino!gmail.com IBM
+cs15btech11007!iith.ac.in Indian Inst of Technology Hyderabad
+olivier.grisel!ensta.org Inria
+khris.richardson!gmail.com Intel
+james!federacy.com James Sulinski
+git!jasonpoon.ca Jason Poon
+steve.coffman!ithaka.org JSTOR
+justin!balduncle.com Justin Johnson

Self?

In cncf-config/email-map:
> +justin!balduncle.com Justin Johnson
+vkamra!kasten.io Kasten
+nielslensink!gmail.com KPN
+timothee.faure!cegetel.net Le Mas des Papillons
+s.rabot!lectra.com Lectra
+lo!linux.com Linux.com
+liz!lizrice.com Liz Rice
+henrik!loodse.com Loodse GmbH
+julian!simioni.org Mapzen
+wbuchwalter!gmail.com Microsoft
+shimin.guo!mixpanel.com Mixpanel
+junaid18183!gmail.com Mode Media
+casey!monax.io Monax
+jp!moogsoft.com Moogsoft
+chrismytton!gmail.com mySociety
+du!njtech.edu.cn Nanjing University of  [...]

2017-11-03 13:52 UTC, radoslaw commented
all requested changes are done

2017-11-03 16:15 UTC, lukaszgryglicki commented
A lot of emails moved from one place to another, probably caused by sort but with some nonstandard LANG/LC_ALL.
This makes this PR unreviewable. My chrome and safari hang when I try to make a review due to an astronomical number of changes.

We also want to keep two first lines (staring with a comment `# `)

Please make sure that You sort using standard ASCII sorting order.
To do so on Linux You can use:
> `unset LC_ALL`
> `unset LANG`
> `cat email-map | sort | uniq > out`
Now out should not differ from email-map
> `diff email-map out` (it can eventually say "No newline at the end of file").

Without sorting that way I'm unable to review changes.

2017-11-03 18:12 UTC, dankohn commented
Almost all of your uses of HP should be HPE. They're separate companies now.

2017-11-03 18:13 UTC, radoslaw commented
done, changes pushed 
Rad
 

    On Friday, November 3, 2017, 5:15:20 PM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
A lot of emails moved from one place to another, probably caused by sort but with some nonstandard LANG/LC_ALL.
This makes this PR unreviewable. My chrome and safari hang when I try to make a review due to an astronomical number of changes.

We also want to keep two first lines (staring with a comment #)

Please make sure that You sort using standard ASCII sorting order.
To do so on Linux You can use:


unset LC_ALL
unset LANG
cat email-map | sort | uniq > out
Now out should not differ from email-map
diff email-map out (it can eventually say "No newline at the end of file").


Without sorting that way I'm unable to review changes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-11-03 18:27 UTC, radoslaw commented
There are 701 emails associated with HP, none of which came from my research. I am not sure what to do for this request.
Rad
 

    On Friday, November 3, 2017, 7:12:25 PM GMT+1, Dan Kohn <notifications@github.com> wrote:  
 
 
Almost all of your uses of HP should be HPE. They're separate companies now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-11-03 18:31 UTC, dankohn commented
Everywhere where you see hpe.com map it to company name HPE. Anything
before 2 years ago as hp.com should also be mapped to HPE.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Fri, Nov 3, 2017 at 2:27 PM, Radoslaw Dziegielewski <
notifications@github.com> wrote:

> There are 701 emails associated with HP, none of which came from my
> research. I am not sure what to do for this request.
> Rad
>
>
> On Friday, November 3, 2017, 7:12:25 PM GMT+1, Dan Kohn <
> notifications@github.com> wrote:
>
>
> Almost all of your uses of HP should be HPE. They're separate companies
> now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/cncf/gitdm/pull/7#issuecomment-341788917>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AC8MBqzcceRXrG7EZOc8TH6kMHBgZFTvks5sy1scgaJpZM4QQE7L>
> .
>

2017-11-03 19:38 UTC, lukaszgryglicki requested changes
Plus @dankohn comments about HP and HPE

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +alostengineer!users.noreply.github.com College of Engineering
Self?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +brk3!users.noreply.github.com Hewlett-Packard
HP or HPE

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +chris!tech9computers.com Tech9 Computer Solutions,
No comma at the end ","

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +clairew!users.noreply.github.com Aperture Laboratories
Possibly Self?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +dirbaio!dirbaio.net Dario Nieuwenhuis
Possibly Self?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +grod!google.com Intellisis  2016-06-15
Missing <, very important, this is Garrett Rodriguez account

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +iamthemuffinman!outlook.com The AME  2014-05-15
Missing <

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +iterion!gmail.com Collanthropy,
No comma at end ,

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +jay.ahn!sk.com KT  2014-02-28
Missing <

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +klausenbusk!hotmail.com SkiTravel  < 2015-03-15
Extra whitespace before <

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +mail!bharr.is Newmount Mining  2014-11-15
Missing <

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +mark_xiett!163.com ZTE  2015-07-10
Missing <

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +matthew.huxtable!sparx.co.uk Sparx - Illuminating Learning
Self?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +mccullya!gmail.com At Work
?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +mike!luedkes.com Jigsaw,
No comma at end.

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +miyurz!users.noreply.github.com Ansible by Red Hat
Possible Ansible or Red Hat?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +muralimmreddy!gmail.com Cloudnative Labs
Self?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +raeesiqbal!users.noreply.github.com Hostingini Pvt.  < 2016-11-15
Extra whitespace before <

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +rohitsharma9204!gmail.com zalando
We use Zalando capitalized afaik.

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +sharnoby3!gmail.com İstanbul Şehir Üniversitesi
Self?

2017-11-03 19:38 UTC, lukaszgryglicki commented on cncf-config/email-map
> +zzxwill!gmail.com NotFound
Why Self changed to NotFound?

2017-11-03 20:46 UTC, radoslaw commented
Something tells me this would not be the last correction iteration of this data.
In search of HP (180 changes were easy but 520 most likely need research), I found this sequence:
cinerama!hp.com HP < 2017-03-08
cinerama!hp.com SUSE
cinerama!hpe.com HPE < 2017-03-08
cinerama!hpe.com SUSE
I think there would be more of cases such as the one above. Should anything be done about them?

Rad
 

    On Friday, November 3, 2017, 8:38:43 PM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
@lukaszgryglicki requested changes on this pull request.
   
   - @dankohn comments about HP and HPE

In cncf-config/email-map:
>  alopgeek!gmail.com AT&T < 2014-05-19
 alopgeek!gmail.com Cisco
+alostengineer!users.noreply.github.com College of Engineering

Self?

In cncf-config/email-map:
> @@ -1223,10 +1276,12 @@ brianh1729!gmail.com Microsoft
 brianlynch!gmail.com Google
 brianphaley!gmail.com HP < 2017-03-10
 brianphaley!gmail.com Red Hat
+brk3!users.noreply.github.com Hewlett-Packard

HP or HPE

In cncf-config/email-map:
> @@ -1524,7 +1597,8 @@ chris!paninetworks.com New Networking
 chris!pistoncloud.com Piston Cloud
 chris!sapho.com Sapho
 chris!slicehost.com Piston Cloud
-chris!tech9computers.com Tech9 Computer Solutions, LLC
+chris!soundshare.co.uk Self
+chris!tech9computers.com Tech9 Computer Solutions,  

No comma at the end ","

In cncf-config/email-map:
>  ck.khullar!gmail.com Intel
 ckleban!gmail.com Google
 cl55_6!hotmail.com Canonical
 cl55_6!hotmail.com IBM < 2014-05-06
 claire921!gmail.com Google
 clairelundeby!gmail.com Self < 2016-05-15
 clairelundeby!gmail.com Veeva Systems
+clairew!users.noreply.github.com Aperture Laboratories

Possibly Self?

In cncf-config/email-map:
>  dino.p!inwinstack.com inwinSTACK
 dipankarsarkar!gmail.com Aurora Borealis technologies
 diparfitt!gmail.com Mozilla
+dirbaio!dirbaio.net Dario Nieuwenhuis

Possibly Self?

In cncf-config/email-map:
>  grmarek!gmail.com Google
 grod!google.com Google
-grod!google.com Intellisis Corporation < 2016-06-15
+grod!google.com Intellisis  2016-06-15

Missing <, very important, this is Garrett Rodriguez account

In cncf-config/email-map:
> @@ -3436,14 +3590,15 @@ iamljj!gmail.com UnitedStack
 iamthemuffinman!outlook.com NextGear Capital < 2016-06-15
 iamthemuffinman!outlook.com Roche < 2016-01-15
 iamthemuffinman!outlook.com SalesForce
-iamthemuffinman!outlook.com The AME Group < 2014-05-15
+iamthemuffinman!outlook.com The AME  2014-05-15

Missing <

In cncf-config/email-map:
>  itayrel!gmail.com NotFound
-iterion!gmail.com Collanthropy, LLC
+iterion!gmail.com Collanthropy,  

No comma at end ,

In cncf-config/email-map:
> @@ -3763,7 +3928,7 @@ jawon.choo!sk.com Samsung < 2016-07-31
 jaxbr503!gmail.com Oregon State Network Enginerring
 jay!apache.org Apache
 jay!jvf.cc Rackspace
-jay.ahn!sk.com KT Corporation < 2014-02-28
+jay.ahn!sk.com KT  2014-02-28

Missing <

In cncf-config/email-map:
> @@ -4615,8 +4813,9 @@ kkalynovskyi!mirantis.com Mirantis
 klaus1982.cn!gmail.com IBM
 klausenbusk!hotmail.com Airtame
 klausenbusk!hotmail.com Airtame < 2015-09-15
-klausenbusk!hotmail.com SkiTravelGroup < 2015-03-15
-klausenbusk!hotmail.com SkiTravelGroup < 2016-04-15
+klausenbusk!hotmail.com SkiTravel  < 2015-03-15

Extra whitespace before <

In cncf-config/email-map:
> @@ -5159,7 +5384,7 @@ maheshkumar.pandurangan!hpe.com HP
 mail!arif-ali.co.uk OCF plc
 mail!bharr.is BHP Billiton < 2012-10-15
 mail!bharr.is Geli
-mail!bharr.is Newmount Mining Corporation < 2014-11-15
+mail!bharr.is Newmount Mining  2014-11-15

Missing <

In cncf-config/email-map:
> @@ -5271,7 +5500,7 @@ mark.washenberger!rackspace.com Nebula
 mark007!gmail.com Self
 mark_klein!cable.comcast.com Comcast
 mark_xiett!163.com Self
-mark_xiett!163.com ZTE Corporation < 2015-07-10
+mark_xiett!163.com ZTE  2015-07-10

Missing <

In cncf-config/email-map:
> @@ -5425,6 +5662,8 @@ matthew.farina!hp.com Samsung
 matthew.farina!hpe.com HP < 2017-06-23
 matthew.farina!hpe.com Innovating Tomorrow < 2017-08-15
 matthew.farina!hpe.com Samsung
+matthew.huxtable!sparx.co.uk Sparx - Illuminating Learning

Self?

In cncf-config/email-map:
> @@ -5496,6 +5737,7 @@ mbutcher!engineyard.com Microsoft
 mbutcher!engineyard.com Nest < 2015-06-15
 mbutcher!engineyard.com Resolv Inc < 2014-10-15
 mca.ashu4!gmail.com One Convergence
+mccullya!gmail.com At Work

?

In cncf-config/email-map:
> @@ -5724,8 +5976,10 @@ mikalv!mikalv.net Kloner AS < 2016-02-15
 mikalv!mikalv.net Knowit Objectnet AS
 mike!fluffypenguin.org Piston Cloud
 mike!kollegienet.dk Foreningen Kollegienet Odense
+mike!luedkes.com Jigsaw,  

No comma at end.

In cncf-config/email-map:
> @@ -5790,6 +6048,7 @@ mitake.hitoshi!lab.ntt.co.jp NTT
 mithil.arun!pluribusnetworks.com Pluribus Networks
 mitsuhiro.tanino!hds.com Hitachi Data Systems
 mixia!google.com Google
+miyurz!users.noreply.github.com Ansible by Red Hat

Possible Ansible or Red Hat?

In cncf-config/email-map:
> @@ -5987,6 +6253,7 @@ munnerz!users.noreply.github.com Jetstack
 murali.reddy!cloudnativelabs.net Apache
 murali.reddy!cloudnativelabs.net Citrix < 2014-11-15
 muralidharan.selvaraj!infinite.com Infinite
+muralimmreddy!gmail.com Cloudnative Labs

Self?

In cncf-config/email-map:
>  radhika.puthiyetath!coreos.com CoreOS
-raees.bhatti!gmail.com The Websmith Co.
-raeesiqbal!users.noreply.github.com Hostingini Pvt. Ltd. < 2016-11-15
+raees.bhatti!gmail.com The Websmith 
+raeesiqbal!users.noreply.github.com Hostingini Pvt.  < 2016-11-15

Extra whitespace before <

In cncf-config/email-map:
> @@ -6990,11 +7301,13 @@ rohan.kanade!nttdata.com Red Hat
 rohitagarwalla!gmail.com Cisco
 rohitgarwalla!gmail.com Cisco
 rohitj!vmware.com VMware
+rohitsharma9204!gmail.com zalando

We use Zalando capitalized afaik.

In cncf-config/email-map:
>  shanthakumar.k!hp.com HP
 shanthakumar.k!hpe.com HP
 shanthakumartk!gmail.com HP
 shaohe.feng!intel.com Intel
 shaohef!126.com Intel
 shaomingwu!inspur.com Inspur
 shapeliang!gmail.com Jd.Com
+sharnoby3!gmail.com İstanbul Şehir Üniversitesi

Self?

In cncf-config/email-map:
> \ No newline at end of file
+zzxwill!gmail.com NotFound

Why Self changed to NotFound?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-11-03 20:56 UTC, lukaszgryglicki commented
I would put HPE in those cases.... but this is just me.... @dankohn ?
Eventually, You can correct all other stuff and all HP cases that You are sure and leave other/unsure untouched.
I'll merge this big PR tomorrow then, and rest of the work will be done in next PR/iteration (I would prefer to review smaller PR).
You can also work on Prometheus emails in the next iteration.
Once all of this is finished (at least this 2nd iteration) I would regenerate data for this repo and update dashboards in cncf/devstats (both k8s and prometheus).

2017-11-03 21:18 UTC, radoslaw commented
all done in this iteration, changes pushed

Rad
 

    On Friday, November 3, 2017, 8:38:43 PM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
@lukaszgryglicki requested changes on this pull request.
   
   - @dankohn comments about HP and HPE

In cncf-config/email-map:
>  alopgeek!gmail.com AT&T < 2014-05-19
 alopgeek!gmail.com Cisco
+alostengineer!users.noreply.github.com College of Engineering

Self?

In cncf-config/email-map:
> @@ -1223,10 +1276,12 @@ brianh1729!gmail.com Microsoft
 brianlynch!gmail.com Google
 brianphaley!gmail.com HP < 2017-03-10
 brianphaley!gmail.com Red Hat
+brk3!users.noreply.github.com Hewlett-Packard

HP or HPE

In cncf-config/email-map:
> @@ -1524,7 +1597,8 @@ chris!paninetworks.com New Networking
 chris!pistoncloud.com Piston Cloud
 chris!sapho.com Sapho
 chris!slicehost.com Piston Cloud
-chris!tech9computers.com Tech9 Computer Solutions, LLC
+chris!soundshare.co.uk Self
+chris!tech9computers.com Tech9 Computer Solutions,  

No comma at the end ","

In cncf-config/email-map:
>  ck.khullar!gmail.com Intel
 ckleban!gmail.com Google
 cl55_6!hotmail.com Canonical
 cl55_6!hotmail.com IBM < 2014-05-06
 claire921!gmail.com Google
 clairelundeby!gmail.com Self < 2016-05-15
 clairelundeby!gmail.com Veeva Systems
+clairew!users.noreply.github.com Aperture Laboratories

Possibly Self?

In cncf-config/email-map:
>  dino.p!inwinstack.com inwinSTACK
 dipankarsarkar!gmail.com Aurora Borealis technologies
 diparfitt!gmail.com Mozilla
+dirbaio!dirbaio.net Dario Nieuwenhuis

Possibly Self?

In cncf-config/email-map:
>  grmarek!gmail.com Google
 grod!google.com Google
-grod!google.com Intellisis Corporation < 2016-06-15
+grod!google.com Intellisis  2016-06-15

Missing <, very important, this is Garrett Rodriguez account

In cncf-config/email-map:
> @@ -3436,14 +3590,15 @@ iamljj!gmail.com UnitedStack
 iamthemuffinman!outlook.com NextGear Capital < 2016-06-15
 iamthemuffinman!outlook.com Roche < 2016-01-15
 iamthemuffinman!outlook.com SalesForce
-iamthemuffinman!outlook.com The AME Group < 2014-05-15
+iamthemuffinman!outlook.com The AME  2014-05-15

Missing <

In cncf-config/email-map:
>  itayrel!gmail.com NotFound
-iterion!gmail.com Collanthropy, LLC
+iterion!gmail.com Collanthropy,  

No comma at end ,

In cncf-config/email-map:
> @@ -3763,7 +3928,7 @@ jawon.choo!sk.com Samsung < 2016-07-31
 jaxbr503!gmail.com Oregon State Network Enginerring
 jay!apache.org Apache
 jay!jvf.cc Rackspace
-jay.ahn!sk.com KT Corporation < 2014-02-28
+jay.ahn!sk.com KT  2014-02-28

Missing <

In cncf-config/email-map:
> @@ -4615,8 +4813,9 @@ kkalynovskyi!mirantis.com Mirantis
 klaus1982.cn!gmail.com IBM
 klausenbusk!hotmail.com Airtame
 klausenbusk!hotmail.com Airtame < 2015-09-15
-klausenbusk!hotmail.com SkiTravelGroup < 2015-03-15
-klausenbusk!hotmail.com SkiTravelGroup < 2016-04-15
+klausenbusk!hotmail.com SkiTravel  < 2015-03-15

Extra whitespace before <

In cncf-config/email-map:
> @@ -5159,7 +5384,7 @@ maheshkumar.pandurangan!hpe.com HP
 mail!arif-ali.co.uk OCF plc
 mail!bharr.is BHP Billiton < 2012-10-15
 mail!bharr.is Geli
-mail!bharr.is Newmount Mining Corporation < 2014-11-15
+mail!bharr.is Newmount Mining  2014-11-15

Missing <

In cncf-config/email-map:
> @@ -5271,7 +5500,7 @@ mark.washenberger!rackspace.com Nebula
 mark007!gmail.com Self
 mark_klein!cable.comcast.com Comcast
 mark_xiett!163.com Self
-mark_xiett!163.com ZTE Corporation < 2015-07-10
+mark_xiett!163.com ZTE  2015-07-10

Missing <

In cncf-config/email-map:
> @@ -5425,6 +5662,8 @@ matthew.farina!hp.com Samsung
 matthew.farina!hpe.com HP < 2017-06-23
 matthew.farina!hpe.com Innovating Tomorrow < 2017-08-15
 matthew.farina!hpe.com Samsung
+matthew.huxtable!sparx.co.uk Sparx - Illuminating Learning

Self?

In cncf-config/email-map:
> @@ -5496,6 +5737,7 @@ mbutcher!engineyard.com Microsoft
 mbutcher!engineyard.com Nest < 2015-06-15
 mbutcher!engineyard.com Resolv Inc < 2014-10-15
 mca.ashu4!gmail.com One Convergence
+mccullya!gmail.com At Work

?

In cncf-config/email-map:
> @@ -5724,8 +5976,10 @@ mikalv!mikalv.net Kloner AS < 2016-02-15
 mikalv!mikalv.net Knowit Objectnet AS
 mike!fluffypenguin.org Piston Cloud
 mike!kollegienet.dk Foreningen Kollegienet Odense
+mike!luedkes.com Jigsaw,  

No comma at end.

In cncf-config/email-map:
> @@ -5790,6 +6048,7 @@ mitake.hitoshi!lab.ntt.co.jp NTT
 mithil.arun!pluribusnetworks.com Pluribus Networks
 mitsuhiro.tanino!hds.com Hitachi Data Systems
 mixia!google.com Google
+miyurz!users.noreply.github.com Ansible by Red Hat

Possible Ansible or Red Hat?

In cncf-config/email-map:
> @@ -5987,6 +6253,7 @@ munnerz!users.noreply.github.com Jetstack
 murali.reddy!cloudnativelabs.net Apache
 murali.reddy!cloudnativelabs.net Citrix < 2014-11-15
 muralidharan.selvaraj!infinite.com Infinite
+muralimmreddy!gmail.com Cloudnative Labs

Self?

In cncf-config/email-map:
>  radhika.puthiyetath!coreos.com CoreOS
-raees.bhatti!gmail.com The Websmith Co.
-raeesiqbal!users.noreply.github.com Hostingini Pvt. Ltd. < 2016-11-15
+raees.bhatti!gmail.com The Websmith 
+raeesiqbal!users.noreply.github.com Hostingini Pvt.  < 2016-11-15

Extra whitespace before <

In cncf-config/email-map:
> @@ -6990,11 +7301,13 @@ rohan.kanade!nttdata.com Red Hat
 rohitagarwalla!gmail.com Cisco
 rohitgarwalla!gmail.com Cisco
 rohitj!vmware.com VMware
+rohitsharma9204!gmail.com zalando

We use Zalando capitalized afaik.

In cncf-config/email-map:
>  shanthakumar.k!hp.com HP
 shanthakumar.k!hpe.com HP
 shanthakumartk!gmail.com HP
 shaohe.feng!intel.com Intel
 shaohef!126.com Intel
 shaomingwu!inspur.com Inspur
 shapeliang!gmail.com Jd.Com
+sharnoby3!gmail.com İstanbul Şehir Üniversitesi

Self?

In cncf-config/email-map:
> \ No newline at end of file
+zzxwill!gmail.com NotFound

Why Self changed to NotFound?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-11-04 06:04 UTC, lukaszgryglicki approved these changes
I'll fix last remining issues manually after merge - I don't want to review this huge PR again.

2017-11-04 06:04 UTC, lukaszgryglicki commented on cncf-config/email-map
> +bluejay.ahn!gmail.com KT  2014-02-28
Still missing <

2017-11-04 06:04 UTC, lukaszgryglicki commented on cncf-config/email-map
> +chaman.kang!gmail.com KT  2014-05-31
Still missing <

2017-11-04 06:04 UTC, lukaszgryglicki commented on cncf-config/email-map
> +cr125rider!gmail.com Media Logic  2014-04-15
:(

2017-11-04 06:04 UTC, lukaszgryglicki commented on cncf-config/email-map
> +dirbaio!dirbaio.net Dario Nieuwenhuis
Not addressed.

2017-11-04 06:04 UTC, lukaszgryglicki commented on cncf-config/email-map
> +git!jasonpoon.ca Jason Poon
Self?

2017-11-04 06:04 UTC, merged

2017-11-04 10:17 UTC, radoslaw commented
dirbaio!dirbaio.net is now Selfgit!jasonpoon.ca is now Microsoft
Rad

    On Saturday, November 4, 2017, 7:04:08 AM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
@lukaszgryglicki approved this pull request.

I'll fix last remining issues manually after merge - I don't want to review this huge PR again.

In cncf-config/email-map:
> @@ -1108,7 +1157,7 @@ blkart.org!gmail.com Eayun
 blp!nicira.com VMware
 blp!ovn.org VMware
 bluebreezecf!gmail.com Huawei
-bluejay.ahn!gmail.com KT Corporation < 2014-02-28
+bluejay.ahn!gmail.com KT  2014-02-28

Still missing <

In cncf-config/email-map:
>  chairmanhh1986!gmail.com NotFound
 chakri!datawisesystems.com Diamanti
-chaman.kang!gmail.com KT Corporation < 2014-05-31
+chaman.kang!gmail.com KT  2014-05-31

Still missing <

In cncf-config/email-map:
> @@ -1746,7 +1825,7 @@ cquiter!gmail.com Clari < 2016-09-15
 cquiter!gmail.com OpenAI < 2016-10-15
 cquiter!gmail.com Otto
 cr125rider!gmail.com AerisWeather
-cr125rider!gmail.com Media Logic Group < 2014-04-15
+cr125rider!gmail.com Media Logic  2014-04-15

:(

In cncf-config/email-map:
>  dino.p!inwinstack.com inwinSTACK
 dipankarsarkar!gmail.com Aurora Borealis technologies
 diparfitt!gmail.com Mozilla
+dirbaio!dirbaio.net Dario Nieuwenhuis

Not addressed.

In cncf-config/email-map:
> @@ -2967,6 +3096,8 @@ git!amanda.darkdna.net DarkDNA
 git!gamma.net.nz Catalyst IT
 git!gg7.io Self
 git!hiltunen.io Self
+git!jasonpoon.ca Jason Poon

Self?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-11-04 11:10 UTC, lukaszgryglicki commented
Please do not respond directly from Your email client. It quotes a lot of data (and most is outdated) - please answer on GitHub UI.
This PR is merged & closed.

2017-12-26 10:43 UTC, lorilorr reviewed
Final $